### PR TITLE
Emayili compatibility update

### LINKED ISSUE #95: Does emayili work with business Outlook?
I am trying to use emayili with my business Outlook. I tried to run this code from what I saw in your unit tests:

```
    ey_em <- emayili::envelope(
        to=to_addr,
        subject="test emayili email",
        html="test emayili email"
    )
    em <- folder$create_email(ey_em)
```

but my `folder `is authenticated with `get_business_outlook()` and my "test emayili email" is a "test.html" file, and I get this error:

`Error: $ operator is invalid for atomic vectors`

### PR DESCRIPTION
**Pull request by hongooi73**
Update emayili code for version 0.6+.

Fixes #95

### CODE REVIEW

File: R/build_email_request.R [hunk 1]
```diff
@@ -40,28 +40,39 @@ build_email_request.blastula_message <- function(body, content_type,
...
 
     if(!is_empty(body$header$Subject))
-        req$subject <- body$header$Subject
+        req$subject <- body$header$Subject$values
+
+    recipients <- build_email_recipients(
+        unclass(body$headers$To$values)$email,
+        unclass(body$headers$Cc$values)$email,
+        unclass(body$headers$Bcc$values)$email,
+        unclass(body$headers$`Reply-To`$values)$email
```
Comment (hongooi73) [inline R/build_email_request.R:72]: @datawookie can you verify that this is the correct way to handle addresses? The `build_email_recipients` function expects its inputs to be character vectors, and I just discovered that emayili uses a custom address class.

Comment (datawookie) [reply R/build_email_request.R:72]: Yes. That will work. Or you can use the accessor functions `to()`, `cc()` etc.

```r
library(emayili)

msg <- envelope(
  to = c("anne@example.com", "bob@example.com")
)

unclass(msg$headers$To$values)$email
#> [1] "anne@example.com" "bob@example.com"
as.character(to(msg))
#> [1] "anne@example.com" "bob@example.com"
```

**Review by datawookie — APPROVED** [review]
Looks good!
